### ISSUE TITLE
Somehow its all blank...

### ISSUE THREAD

**Issue by Zisiki** [eueung/hugo-paper-now#1]
Doesn't matter if you serve on local machine or github pages.
It's all blank.

Have no idea why... I found it lighter than latex, not exactly a tech savvy. Does it mean that I need to rewrite all my previous documents?

**Comment by iblacksand** [comment]
I think this may be because of the browser blocking the style sheets. Firefox blocked loading the sources that weren't `https`. It gave the error message of mixed content. They need to rehost the stylesheets or make it call the website with `https`

**Comment by eueung** [comment]
@Zisiki sorry for late reply :-D..

this template loads all necessary (js) assets from paper-now. Under the hood, it uses a (rather old and quite large) polymer component (which is unmaintained I guess).

yes, it's broken somehow.. this might be issues with the URL or with the changes in the peer-j repo.

I might check this but I don't intend to maintain this port (I'd rather wait for a more lightweight CSS based template for the same purpose).
